apiVersion: v1
kind: Service
metadata:
  name: aceest-api-service
  labels:
    app: aceest-fitness
spec:
  type: LoadBalancer # Or NodePort for Minikube
  selector:
    app: aceest-fitness
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000